# layout -- 布局相关
# language: zh-CN

##menu 导航菜单显示
menu:
- page: 首页
  url: /
  icon: fa-home
- page: 开源
  url: /open-source
  icon:
- page: 招聘
  url: /recruit
  icon:
- page: 书单
  url: /books
  icon: 
- page: 关于
  url: /about
  icon: 


## favicon 
favicon: /favicon.ico

## Feed 
rss: /atom.xml

## 通用时间格式化
date_format: YYYY-MM-DD HH:mm:ss

## widgets
widgets:
- notification
- social
- category
- archive
- tagcloud
- friends

# 各个小工具的设置

## 网站公告设置
notification: 
    name: 王振超，「花名：予尊」
    position: 小米科技 · 服务端研发工程师
    talk: 不断前行，拥抱变化，感恩一路上给予帮助的人！

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/procyon-lotor
 - name: Email
   icon: envelope-o
   href: mailto:zhenchao.wang@hotmail.com
 - name: 联系QQ
   icon: qq
   href: /
 - name: 微博
   icon: weibo
   href: /
 - name: QQ群
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1
   format: MMMM

## 彩色标签云设置
tagcloud_config:
   min_font: 1
   max_font: 1
   unit: em
   amount: 100
   color: true
   orderby: 'count'

## 友链设置
links:
  - 武汉大学NLP研究中心: http://nlp.whu.edu.cn


# 自定义内容设置

## 添加版权保护 
archiveCopyright:
  enable: true
  tip: '版权所有，转载请注明出处'


## 当无目录时的显示文字，默认为'无'
noCategoryText: '无'

## 过低版本的浏览器提醒文字
outdated_browser_text: '你使用的浏览器版本过低，为了你更好的阅读体验，请更新浏览器的版本或者使用其他现代浏览器，比如Chrome、Firefox、Safari等。'

## 文章过期提醒功能
warning:
  days: 3650 
  text: '本文于%d天之前发表，文中内容可能已经过时。'


## 首页文章简介的图片占位符
placeholder: ./img/loading.gif

## 首页文章简介的图片
defaultImgs:
  - /img/default.png

### 截取文章首页描述字数
excerptLength: 120

## 代码高亮配置
highlightTheme: github


## 版权声明文字，支持html/text，但不要使用<li>标签
cc: |-
      <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/" target="_blank">
      本博客所有文章除特别声明外，均采用 CC BY-NC-SA 3.0 许可协议
      </a>


## 主题评论
### gitment
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10


###友言评论
uyan:
  enable: true
  uyan_id: 2081622


# changyan
changyan:
  enable: false
  appid: cysVsEtac
  appkey: 966bea4f406651be0a6c237e63a2cd51
  
# jiathis
jiathis:
  enable: true
  uid: 2081622

## 网盟CNZZ网站统计
cnzz_anaylytics: 1258616757

## 百度网站统计
baidu_anaylytics: 

## 百度文章推送
baidu_push:

## ICON配置
fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

#网站主题配置
since: 2017
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all，搜索 `meta name="robots"` 或请参考： https://support.google.com/webmasters/answer/79812?hl=zh-Hans
version: 1.1.0
